const data = {
    products: [
        {
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality shirt',
        },
        {
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'High quality shirt',
        },
        {
            name: 'Lacoste Slim Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.5,
            numReviews: 17,
            description: 'High quality shirt',
        },
        {
            name: 'Nike Slim Pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 80,
            countInStock: 12,
            brand: 'Nike',
            rating: 5,
            numReviews: 3,
            description: 'High quality pants',
        },
        {
            name: 'Puma Slim Pants',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 65,
            countInStock: 30,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality pants',
        },
        {
            name: 'Adidas Slim Pants',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 85,
            countInStock: 40,
            brand: 'Adidas',
            rating: 5,
            numReviews: 32,
            description: 'High quality pants',
        }
    ]
}

export default data;